source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BrightFreddy_Example' do
  pod 'BrightFreddy', :path => '../'
end

target 'BrightFreddy_Tests' do
  pod 'BrightFreddy', :path => '../'
end
