# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
podfile: Example/Podfile
#xcode_workspace: Example/BrightFreddy.xcworkspace
#xcode_scheme: BrightFreddy-Example

script:
  - xctool -workspace Example/BrightFreddy.xcworkspace -scheme BrightFreddy-Example -sdk iphonesimulator9.3 build

# cache: cocoapods
# podfile: Example/Podfile
#before_install:
#- rvm get stable
#- rvm install ruby-2.2.4
#- rvm use ruby-2.2.4
#- gem install cocoapods # Since Travis is not always on latest version
#- pod install --project-directory=Example
#script:
#- set -o pipefail && xcodebuild test -workspace Example/BrightFreddy.xcworkspace -scheme BrightFreddy-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
